version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MARIADB_ROOT_PASSWORD: mariaUndNichtMongo
